import type { Metadata } from "next";
import "./globals.css";
import { SolanaProviders } from "../../components/SolanaProviders";
import ClientOnly from "../../components/ClientOnly";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientOnly fallback={<div>Loading...</div>}>
          <SolanaProviders>{children}</SolanaProviders>
        </ClientOnly>
      </body>
    </html>
  );
}
